 CREATE TABLE ZF_PROCESS 
   (ID VARCHAR(64) NOT NULL, 
	NAME VARCHAR(64), 
    STATE INT, 
	CONTENT TEXT,
	CREATETIME VARCHAR(30), 
	UPDATETIME VARCHAR(30), 
	 PRIMARY KEY (ID)
	 )comment='table for storing process entities';
     
     
CREATE TABLE ZF_FLOW 
   (ID VARCHAR(64) NOT NULL, 
	NAME VARCHAR(100), 
	PROCESSID VARCHAR(64), 
	PROCESSNAME VARCHAR(100), 
	STATE VARCHAR(20), 
	VARIABLES VARCHAR(4000), 
	CREATETIME VARCHAR(30), 
	UPDATETIME VARCHAR(30), 
	FINISHTIME VARCHAR(30), 
	FATHER_FLOW_ID VARCHAR(64),
	 PRIMARY KEY (ID)
  )comment='table for process executions';
  
  
  CREATE TABLE ZF_SCHEDULE 
   (ID VARCHAR(64) NOT NULL, 
	PROCESSID VARCHAR(64) NOT NULL, 
	FLOWNAME VARCHAR(64) NOT NULL, 
	CRON VARCHAR(64) NOT NULL, 
	VARIABLES VARCHAR(4000), 
	STATE int NOT NULL, 
	CREATETIME VARCHAR(30), 
	UPDATETIME VARCHAR(30),  
	 PRIMARY KEY (ID)
	 )COMMENT='table for timed plans';
     
     
  CREATE TABLE ZF_TASK
   (ID VARCHAR(64) NOT NULL, 
	NAME VARCHAR(64), 
	FLOWID VARCHAR(64), 
	FLOWNAME VARCHAR(64), 
	PROCESSID VARCHAR(64), 
	PROCESSNAME VARCHAR(64), 
	STATE VARCHAR(20), 
	VARIABLES VARCHAR(4000), 
	CREATETIME VARCHAR(30), 
	UPDATETIME VARCHAR(30), 
	FINISHTIME VARCHAR(30), 
	SETTLEDATE VARCHAR(30), 
	NODE VARCHAR(60), 
	MESSAGE VARCHAR(500), 
	 PRIMARY KEY (ID)
   )COMMENT='table for task executions';
